### ISSUE TITLE
issue (might be a problem on my end)

### ISSUE THREAD

**Issue by JustaGoat** [UnityPluginManager/SlimeRancher.DebugMenu#4]
for some reason (it might just be my game i am not sure) when loading the game starts and you can play but the loading screen covers it. its a problem on my end sorry for posting it.

**Comment by DaZombieKiller** [comment]
I'm not entirely sure what this issue is, unfortunately.
Would you be able to provide some screenshots or a short video to illustrate the problem?

**Comment by JustaGoat** [comment]
sorry for the late response. i found the problem it was because i had multimod installed and it requires a mod manager and that mod manager had problems detecting srdebug because it wasn't in mods it was in plugins so moved it and it fixed it.

**Comment by DaZombieKiller** [comment]
No worries, thanks for letting me know! I'll close this issue then, since fixing it seems out of scope (at least for now).
