### ISSUE TITLE
The menu is not working

### ISSUE THREAD

**Issue by Pikachu20489** [UnityPluginManager/SlimeRancher.DebugMenu#9]
I got the mod and I have tried multiple times to open the command menu by pressing B but its not working

**Comment by DaZombieKiller** [comment]
This mod isn't being updated anymore, it was written for a much older version of the game. I don't think it will work properly with the current version of Slime Rancher. You will need to look for alternatives like the [Cheat Menu](https://steamcommunity.com/app/433340/discussions/0/3397295779079958505/) mod.
